### ISSUE TITLE
Find better icons

### ISSUE THREAD

**Issue by jceb** [identinet/identinet-plugin#30]
The current icons are not so great:

* none: gray - good, it stays out of the way and indicates that there's a lack of information available.

![image](https://github.com/identinet/identinet-plugin/assets/101593/6c2e00c9-0b96-4aad-ac9e-6be53af4b47a)

* broken: red - good, however the small `x` in the middle of the shield is difficult to identify.
   * maybe use the crossed out shield with a red exclamation point

![image](https://github.com/identinet/identinet-plugin/assets/101593/1b13e6a8-08ba-43b5-a052-b3651d7cc20a)

or inverted

![image](https://github.com/identinet/identinet-plugin/assets/101593/cdd680d5-8b8d-491a-9899-9f19caaeebb0)

* id: green check mark - difficult to notice. I'd rather have something with a bit more presence.
   * Maybe a blue shield or a simple blue ID badge.

![image](https://github.com/identinet/identinet-plugin/assets/101593/22813374-20b2-4c65-8474-e5e610605419)

![image](https://github.com/identinet/identinet-plugin/assets/101593/636535cf-8a6e-45ec-8316-c0dae4bd1b49)

* id + data: green shield with plus sign - okay, I'd prefer something different
   * Maybe, a plain green shield, a checkered shield or a ID card with text

![image](https://github.com/identinet/identinet-plugin/assets/101593/8bd0891a-0223-4535-a9f1-dff7eb322ca2)

![image](https://github.com/identinet/identinet-plugin/assets/101593/97c02c58-3d5a-4c6e-b58c-4efa2143aa60)

![image](https://github.com/identinet/identinet-plugin/assets/101593/62531334-372d-468f-927c-f350131be708)

In general, the shield metaphor is good, however firefox uses it to show privacy information for pages.

![image](https://github.com/identinet/identinet-plugin/assets/101593/8f0e7888-537a-4b5b-a746-fd6ee0074ea5)

Maybe there are better icons somewhere: https://fontawesome.com/search

**Comment by jceb** [comment]
@simne7 what do you think?

**Comment by jceb** [comment]
![x](https://github.com/identinet/identinet-plugin/assets/101593/885d772e-8aeb-4671-bf3e-6c1e98f55ae1)

@simne7 what do you think?

**Comment by simne7** [comment]
- gray: I'd rotate it by 90° -> strike through bar goes top left to bottom right (search for "slash" on fontawesome)
- red: what about the "x" instead of the exclamation mark? Or a flash?
- blue: it's the DID-only case, right? I personally don't like the "i" - what does it tell me? Reminds me too much of "information". What about stacking the gray cert with an abstract ID card icon? 
- green: nah, what does that burger icon inside mean? ;) what about a simple check mark?


![image](https://github.com/identinet/identinet-plugin/assets/1122451/fecf5d71-fd71-444a-a517-5634d8fb4477)
